### PR TITLE
Fix/repo

### PR DESCRIPTION
**Pull request by tessus**
I think you committed the `.swp` file and the `target` dir by accident.

I also added a `.gitignore` so that this doesn't happen again.

### CODE REVIEW

**Review by ba9f11ecc3497d9993b933fdc2bd61e5 — APPROVED** [review]

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
I merged your changes (thanks!)  but had to clone it back to my gitea server (this is just a mirror from my gitea)

**Comment by tessus** [comment]
> thanks!

you're welcome.

> had to clone it back to my gitea server

I am not entirely sure what you mean by that. You only have to push the changes from a local work dir to your gitea repo.

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
> You only have to push the changes from a local work dir to your gitea repo.

This is what I meant.

looking at the error message you mentioned for the Unique Local addresses type,  it was properly detected, but the mask was checked with a wrong function (that works for Unicast and Link-Local)

**Comment by tessus** [comment]
> This is what I meant.

Hmm, something is off. What I meant was, you use the merge function (button) or merge via commandline in github. In this case, my commits are also attribute to me. I don't really care, but others might not be so happy to not have their name associated with their code change. Or when you work on the command line in your git work dir, you just have to pull the PR and merge to master. A work dir can have multiple remotes.
Then you push the master branch to the remote that is your gitea repo.

When you check your master branch, there is no commit from me. I do not even know how you managed to remove me as the author during the merge process. As I said I don't care, but this is not how git works.

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
oh, sorry. I stopped using git hub a while back and only use the mirror functionality provided by gitea (which is probably what removed you as an author) I will look into improving my workflow with the multiples remotes you mentioned

**Comment by tessus** [comment]
no worries, you still have a local repo where you do the development.

If you have any questions how to work with gitea and github, pleae let me know. If your gitea instance is public you could create a user and a test repo for me and I can show you in 5 minutes how to do this.

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
Thanks for the advice, I did setup multiples remotes and I am able to merge a test branch from github to gitea.

```
git branch --remote
  gitea/master
  github/master
  github/test-branch
```

but when I try to switch to branch github/master, my head gets immediately detached. I believe this is caused by having 2 branches with the name "master" can you confirm?

if this is the case, I believe the strategy will not be compatible with gitea mirroring function (take all branches from gitea (including master) and mirror them to github). I could rename branches and disable mirroring when/if I have collaborators.

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
although I have made a public organisation in gitea (running in a lxc rootless container), I decided not to expose it to the internet to reduce surface attack since I also have private repos in there. It is great to share my work without relying on github or exposing a service, but not so great for collaboration.

Another strategy would be to keep sync on but prefix my branches with "gitea" or "github", that way, I could merge a branch from github to both.

If you have a better idea, I am all ears.

**Comment by tessus** [comment]
It's not much different than having 2 remote repos/forks.
It's way past my bed time. I'll write up a guide tomorrow.

**Comment by tessus** [comment]
# Intro

Let's start from scratch. I am going to use `USERNAME` as the place holder for the gh username in the repo address.

Lets say you have a repo called `test` on gitea.

# Create a repo on github

Create the repo `test` under your username. The repo address is: `git@github.com:USERNANE/test.git`

# Clone the gitea repo

```
git clone git@gitea.example.com:test.git
cd test
```

You now have a remote called `origin` that points to your gitea repo.

Now you have to add the github repo as an additional remote:

```
git remote add github git@github.com:USERNANE/test.git
```

# Push your code to github

You do not have to do this step, if you already have a repo on github that is in sync with your gitea repo.
But since we are starting from scratch, here we go:

```
git push github master
```

Now the repos are in sync.

# Merge a PR on github

Someone creates a PR on github. There are several ways to merge it. For the sake of easiness, let's just use the `Merge` button on the github web site.
Now the new code is in the master branch of the github repo.

# Pull master branch from github

In your working dir you are in the state that you were before. The code is in sync with gitea, so we have to get the changes from github:

```
git pull github master
```

Now the code is in sync with github, and we have to update the gitea repo.

# Push to gitea

```
git push origin master
```

You actually do not have to specify `origin master` here, because `origin` and `master` are your defaults, since you cloned from gitea.
But it is good to have it for reference. Also when you work with different branches you just replace `master` with the branch name.

Now both repos are in sync.

Done.

**Pull request merged**
